#!/usr/bin/env bash
#
# Bash script for provisioning the AEM author instances

set -e
set -x

function config(){
	export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
	export CLIENT_FQDN=`hostname`
	export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
	echo "Configuring /etc/hosts ..."
	echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
	echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
	echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_aem(){
	export AEM_ROOT=/home/vagrant/aem
	export AEM_USER=aem
	##TODO need to change this for a more suitable setting
	export MONGODB_URI=mongodb://192.168.19.100
	echo "Create folders under shared vagrant dir"
	mkdir /home/vagrant/aem
	chmod 777 /home/vagrant/aem

	echo "Copy cq-author from shared folder"
	ls /vagrant
	cp /vagrant/cq-author-p4503.jar $AEM_ROOT/.
	
	echo "RUN -> java -Xmx2g -XX:MaxPermSize=512m -jar $AEM_ROOT/cq-author-p4503.jar -r crx3,crx3mongo -Doak.mongo.uri=\"$MONGODB_URI\""
}

function update_repo(){
	echo "Update Repositoryies"
	sudo apt-get update -y
}

function install_java(){
	echo "Install Java"
	wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh
	bash equip_java7_64.sh
}


function create_aem_daemon(){
	echo "Create AEM /etc/init.d/aem"
	#following AEM docs - https://helpx.adobe.com/experience-manager/kb/linux-init-script.html

	sudo echo "
	#!/bin/sh

	### BEGIN INIT INFO
	# Provides:             aem
	# X-Start-Before:
	# X-Stop-After:
	# Default-Start:        2 3 4 5
	# Default-Stop:         0 1 6
	# Description:          Runs the aem services
	# Short-Description:    Runs the aem service
	### END INIT INFO
	. /lib/lsb/init-functions
	BIN=${AEM_ROOT}/crx-quickstart/bin

	case \"${1}\" in
		start)

			log_daemon_msg \"Starting aem daemon\" \"aem\"
			start-stop-daemon --start --quiet --pidfile /var/run/aem.pid --exec $BIN/start --test > /dev/null || exit 1
			start-stop-daemon --start --quiet --pidfile /var/run/aem.pid --exec $BIN/start -- --background /var/run/aem.pid || exit 2
			log_end_msg 0
			;;

		stop)
			log_daemon_msg \"Stopping aem daemon\" \"aem\"
			start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile /var/run/aem.pid --exec $BIN/stop
			RETURN=\"${?}\"
			[ \"${RETURN}\" = 2 ] && exit 2
			# Many daemons don't delete their pidfiles when they exit.
			rm -f /var/run/aem.pid
			log_end_msg 0
			;;

		force-reload|restart)
			${0} stop
			${0} start
			;;

		*)
			log_success_msg \"Usage: ${0} {start|stop|restart|force-reload}\"
			exit 1
			;;
	esac
	" > /etc/init.d/aem
	sudo cat /etc/init.d/aem
	sudo chmod 755 /etc/init.d/aem
}

config
update_repo
install_java
install_aem
echo "DONE"
