# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/vagrant"

  (0..2).each do |i|

    config.vm.define "mongod#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.name = "mongod#{i}"
        vb.memory = 4096
      end
      server.vm.hostname = "mongod#{i}.mongodb.course"
      server.vm.network :private_network, ip: "192.168.15.10#{i}"
      server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
    end
  end

end
