Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.define "mongod" do |mongod|

      mongod.vm.provider "virtualbox" do |v|
         v.customize ["modifyvm", :id, "--cpus", "2", "--memory", "3072"]
      end

      mongod.vm.network :private_network, ip: "192.168.14.100"
      mongod.vm.hostname = "mongodb.mongodb.course"
      mongod.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
    end
end
