# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "./shared/", "/vagrant/"
  config.vm.box_check_update = false
  config.vm.define "mongod" do |mongod|
    mongod.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "2", "--memory", "2048"]
      v.name = "mongod-chapter2"
    end

    mongod.vm.network :private_network, ip: "192.168.12.100"
    mongod.vm.hostname = "mongodb.mongodb.course"
    mongod.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
  end
end
