# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "./shared/", "/vagrant/"
  config.vm.define "mongod" do |server|
      server.vm.provider "virtualbox" do |vb|
	      vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.name = "mongod"
        vb.memory = 2048
      end
      server.vm.hostname = "mongod.mongodb.course"
      server.vm.network :private_network, ip: "192.168.11.100"
      server.vm.provision :shell, path: "provision-mongod", args: ENV['ARGS']
    end
end
