# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.synced_folder "../../AEM/author", "/vagrant/"
  config.vm.define "aem" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.name = "aem"
      vb.memory = 3072
    end
  	server.vm.hostname = "aem.mongodb.course"
  	server.vm.network :private_network, ip: "192.168.11.101"
  	server.vm.provision :shell, path: "provision-aem", args: ENV['ARGS']
  end
end
