#!/usr/bin/env bash
#
# Bash script for provisioning the AEM author instances

set -e
set -x

function config(){
	export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
	export CLIENT_FQDN=`hostname`
	export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
	echo "Configuring /etc/hosts ..."
	echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
	echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
	echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_mongod(){
	echo "Install MongoDB Enterprise"
	sudo apt-get install -y --force-yes mongodb-enterprise=3.0.8 mongodb-enterprise-server=3.0.8 mongodb-enterprise-shell=3.0.8
	sudo killall mongod
	mkdir -p /home/vagrant/data
	chmod -R 777 /home/vagrant/data
	chown -R mongodb:mongodb /home/vagrant/data

  cp /vagrant/mongod.conf /home/vagrant

  echo "Set LC_ALL=C to .profile"
  sudo echo "export LC_ALL=C" >> /home/vagrant/.profile
}

function update_repo(){
	echo "Install MongoDB Enterprise Repository"
	echo "deb http://repo.mongodb.com/apt/ubuntu "$(lsb_release -sc)"/mongodb-enterprise/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
	echo "Update Repositoryies"
	sudo apt-get update -y
	echo "Installing MongoDB Enterprise Dependencies"
	sudo apt-get install -y libgssapi-krb5-2 libsasl2-2 libssl1.0.0 libstdc++6 snmp

}

function config(){
	echo "Disable THP - http://docs.mongodb.org/master/tutorial/transparent-huge-pages/"
	echo "
	#!/bin/sh
	### BEGIN INIT INFO
	# Provides:          disable-transparent-hugepages
	# Required-Start:    $local_fs
	# Required-Stop:
	# X-Start-Before:    mongod mongodb-mms-automation-agent
	# Default-Start:     2 3 4 5
	# Default-Stop:      0 1 6
	# Short-Description: Disable Linux transparent huge pages
	# Description:       Disable Linux transparent huge pages, to improve
	#                    database performance.
	### END INIT INFO
	case $1 in
	  start)
	    if [ -d /sys/kernel/mm/transparent_hugepage ]; then
	      thp_path=/sys/kernel/mm/transparent_hugepage
	    elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]; then
	      thp_path=/sys/kernel/mm/redhat_transparent_hugepage
	    else
	      return 0
	    fi
	    echo 'never' > ${thp_path}/enabled
	    echo 'never' > ${thp_path}/defrag
	    unset thp_path
	    ;;
	esac
	" > /etc/init.d/disable-transparent-hugepages
	sudo chmod 755 /etc/init.d/disable-transparent-hugepages
	sudo update-rc.d disable-transparent-hugepages defaults
  #sudo su
  echo never > /sys/kernel/mm/transparent_hugepage/enabled
  echo never > /sys/kernel/mm/transparent_hugepage/defrag

}


config
update_repo
install_mongod
echo "DONE"
