#!/usr/bin/env bash
#
# Bash script for provisioning the AEM author instances

set -e
set -x

function config(){
	export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
	export CLIENT_FQDN=`hostname`
	export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
	echo "Configuring /etc/hosts ..."
	echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
	echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
	echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_aem(){
  export AEM_JAR=/vagrant/cq-author-p4502.jar
  export AEM_ROOT=/home/vagrant/aem
	export AEM_USER=aem
	##TODO need to change this for a more suitable setting
	export MONGODB_URI=mongodb://192.168.14.100
	echo "Create folders under shared $AEM_ROOT dir"
	mkdir $AEM_ROOT
	chmod 777 $AEM_ROOT
	echo "RUN -> java -Xmx2g -XX:MaxPermSize=512m -jar $AEM_JAR -r crx3,crx3mongo -Doak.mongo.uri=\"$MONGODB_URI\" -nobrowser -fork"
}

function update_repo(){
	echo "Update Repositories"
	sudo apt-get update -y
}

function install_java(){
	echo "Install Java"
	wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh
	bash equip_java7_64.sh
}

config
update_repo
install_java
install_aem
echo "DONE"
