# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  (1..2).each do |i|
    config.vm.synced_folder "../../AEM/author", "/vagrant/"
    config.vm.define "aem#{i}" do |server|
      server.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--cpus", "2"]
          vb.name = "aem#{i}"
          vb.memory = 4096
      end
      server.vm.hostname = "aem#{i}.mongodb.course"
      server.vm.network :private_network, ip: "192.168.14.10#{i}"
      server.vm.provision :shell, path: "provision-aem", args: ENV['ARGS']
    end
  end
end
